[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = .

[coverage:run]
omit =
    custom_components/private_hacs/__init__.py
    custom_components/private_hacs/config_flow.py
    custom_components/private_hacs/panel.py
